parameters:
  configuration: Debug
  testArguments: ""
  altLocale: ""

steps:

- task: Bash@3
  displayName: hooks/check-bom
  inputs:
    targetType: filePath
    filePath: hooks/check-bom

- task: UseDotNet@2
  displayName: Install .NET Core SDK
  inputs:
    packageType: sdk
    version: 3.1.101
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: CmdLine@2
  displayName: dotnet --version
  inputs:
    script: dotnet --version

- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: build
    arguments: --configuration ${{ parameters.configuration }}

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: >-
      --configuration ${{ parameters.configuration }}
      ${{ parameters.testArguments }}
  env:
    TURN_SERVER_URL: ${{ parameters.turnServerUrl }}
  timeoutInMinutes: 10

# Run tests with an alternative locale configuration
- task: DotNetCoreCLI@2
  displayName: dotnet test (${{ parameters.altLocale }})
  condition: ne('${{ parameters.altLocale }}', '')
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: >-
      --configuration ${{ parameters.configuration }}
      ${{ parameters.testArguments }}
  env:
    TURN_SERVER_URL: ${{ parameters.turnServerUrl }}
    LANG: ${{ parameters.altLocale }}
    LANGUAGE: ${{ parameters.altLocale }}
    LC_ALL: ${{ parameters.altLocale }}
  timeoutInMinutes: 10

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '$(Agent.TempDirectory)/*.trx'
