parameters:
  configuration: Debug
  testArguments: -verbose

steps:

- task: NuGetCommand@2
  displayName: nuget install xunit.runner.console
  inputs:
    command: custom
    arguments: install xunit.runner.console

- task: PowerShell@2
  displayName: Set TargetFramework to net471 by force
  inputs:
    targetType: inline
    script: |
      $projs = (gci *.Tests/*.Tests.csproj) + (gci Libplanet.Benchmarks/*.csproj)
      foreach ($path in $projs) {
        [xml]$csproj = Get-Content $path
        foreach ($pg in $csproj.Project.PropertyGroup) {
          if ($pg.TargetFramework -ne $null) {
            $pg.TargetFramework = "net471"
          }
        }
        $csproj.Save($path)
      }

- task: MSBuild@1
  inputs:
    solution: Libplanet.sln
    msbuildVersion: "16.0"
    configuration: ${{ parameters.configuration }}
    msbuildArguments: /restore

- task: Bash@3
  displayName: xunit.console.exe *.Tests.dll
  inputs:
    targetType: inline
    script: |
      # Because Libplanet.RocksDBStore.Tests has Libplanet.Tests as a dependency,
      # Libplanet.Tests is executed twice without this.
      for f in *.Tests; do
        ${{ parameters.testPrefix }} \
          xunit.runner.console.*/tools/net471/xunit.console.exe \
            $(pwd)/"$f"/bin/${{ parameters.configuration }}/net*/"$f".dll \
            ${{ parameters.testArguments }}
      done
  env:
    TURN_SERVER_URL: ${{ parameters.turnServerUrl }}
    MONO_THREADS_SUSPEND: preemptive
  timeoutInMinutes: 10
